export const routesPaths = {
  home: '/',
  login: '/login',
  class: '/curso/:courseId/aula/:aulaId',
  profile: '/perfil',
  notFound: '/info',
  adminDashboard: '/admin/dashboard',
  adminSettings: '/admin/settings',
  adminEnrollments: '/admin/enrollments',
  adminUsers: '/admin/users',
  adminUserCreation: '/admin/users/create',
  adminUserEdition: '/admin/users/edit/:userId',
  adminCourses: '/admin/courses',
  adminClasses: '/admin/classes',
  adminExams: '/admin/exams',
  adminCalendar: '/admin/calendar',
}
